# Maintainer: Axel ROTTHIER "Drack0rr"
# Update: 2023-05-28

#& type: 3
#& title: Bookstack
#& description: BookStack is a simple, self-hosted, easy-to-use platform for organising and storing information
#& note: Website: <a href='https://www.bookstackapp.com/' target='_blank' rel='noopener'>bookstackapp.com</a>
#& categories: SelfHosted, Wiki, Drack0rr
#& platform: linux
#& logo: https://avatars.githubusercontent.com/u/20912696?s=200&v=4

#% SERVICE: Name of the service (No spaces or points) [bookstack]
#% DB_USER: Database user (No spaces or points) [bookstack_user]
#% DB_PASSWORD: Database user password
#% DB_ROOT_PASSWORD: Database root password
#% DATA_LOCATION: Data localization (Example: /apps/service) [/apps]
#% URL: Service URL (Example: service.rotthier.net or service.com)
#% NETWORK: Your Traefik network (Example: proxy) [proxy]
#% TIME_ZONE: Time zone (Example : Europe/Paris) [Europe/Paris]

version: "3.8"

services:
  bookstack_db:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: $SERVICE-db
    restart: unless-stopped
    volumes:
      - $DATA_LOCATION/$SERVICE/db:/config
    environment:
      - TIMEZONE=$TIME_ZONE
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_PASSWORD
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - default
    labels:
      - "autoupdate=true" # https://github.com/Drack0rr/container-updater
      - "autoupdate.webhook="

#BOOKSTACK Container
  bookstack:
    image: lscr.io/linuxserver/bookstack:latest
    container_name : $SERVICE
    restart: unless-stopped
    volumes:
      - $DATA_LOCATION/$SERVICE/config:/config
    environment:
      - TIMEZONE=$TIME_ZONE
      - APP_URL=https://$URL
      - DB_HOST=bookstack_db
      - DB_PORT=3306
      - DB_USER=$DB_USER
      - DB_PASS=$DB_PASSWORD
      - DB_DATABASE=bookstackapp
    depends_on:
      - bookstack_db
    healthcheck:
      test: curl --fail http://localhost || exit 1
      interval: 1m
      timeout: 30s
      retries: 3
    networks:
      - default
    labels:
      - "autoupdate=true" # https://github.com/Drack0rr/container-updater
      - "autoupdate.webhook="
      - "traefik.enable=true"
      - "traefik.http.routers.$SERVICE.entrypoints=https"
      - "traefik.http.routers.$SERVICE.rule=Host(`$URL`)"
      - "traefik.http.routers.$SERVICE.tls=true"
      - "traefik.http.services.$SERVICE.loadbalancer.server.port=80"
      - "traefik.docker.network=$NETWORK"

networks:
  default:
    external:
      name: $NETWORK