# Maintainer: Axel ROTTHIER "Drack0rr"
# Update: 2023-01-24

#& type: 3
#& title: HomeChart
#& description: Homechart is a productivity application to manage your household data--budgets, tasks, recipes, and more.
#& note: Website: <a href='https://homechart.app/' target='_blank' rel='noopener'>Homechart.app</a>
#& categories: SelfHosted, Drackorr
#& platform: linux
#& logo: https://homechart.app/images/homechart.8143d29cfd822a29044c24fdbb24a64dd2e897bdc081a288f7bbf39f02bfe3ba.png

#% SERVICE: Name of the service (No spaces or points) [homechart]
#% DATA_LOCATION: Data localization (Example: /apps/service) [/apps]
#% URL: Service URL (Example: service.rotthier.net or service.com)
#% NETWORK: Your Traefik network (Example: proxy) [proxy]
#% DB_USER: Database user (No spaces or points) [homechart_user]
#% DB_PASSWORD: Database user password
#% TIME_ZONE: Time zone (Example : Europe/Paris) [Europe/Paris]

# Work with Portainer
version: "3.8"
services:
  homechart:
    image: candiddev/homechart:latest
    restart: always
    container_name: $SERVICE
    depends_on:
      - homechart-db
    environment:
      - TZ=$TIME_ZONE
      - HOMECHART_POSTGRESQL_HOSTNAME=homechart-db
      - HOMECHART_POSTGRESQL_DATABASE=homechart_db
      - HOMECHART_POSTGRESQL_PASSWORD=$DB_PASSWORD
      - HOMECHART_POSTGRESQL_USERNAME=$DB_USER
      - HOMECHART_APP_BASEURL=$URL
      - HOMECHART_APP_SIGNUPDISABLED=True
    labels:
      - "autoupdate=true" # https://github.com/Drack0rr/container-updater
      - "autoupdate.webhook="
      - "traefik.enable=true"
      - "traefik.http.routers.$SERVICE.entrypoints=https"
      - "traefik.http.routers.$SERVICE.rule=Host(`$URL`)"
      - "traefik.http.routers.$SERVICE.tls=true"
      - "traefik.http.services.$SERVICE.loadbalancer.server.port=3000"
      - "traefik.docker.network=$NETWORK"
    networks:
      - default

  homechart-db:
    image: postgres:14
    container_name: $SERVICE-db
    volumes:
      - $DATA_LOCATION/$SERVICE/db:/var/lib/postgresql
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: homechart_db
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DB_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
    labels:
      - "autoupdate=monitor" # https://github.com/Drack0rr/container-updater
    networks:
      - default

networks:
  default:
    external:
      name: $NETWORK