# Maintainer: Axel ROTTHIER "Drack0rr"
# Update: 2022-05-10

#& type: 3
#& title: Vaultwarden
#& description: Password manager
#& note: Website: <a href='https://github.com/dani-garcia/vaultwarden' target='_blank' rel='noopener'>Github.com</a>
#& categories: SelfHosted, Drack0rr
#& platform: linux
#& logo: https://img.papamica.com/logo/bitwarden.png

#% SERVICE: Name of the service (No spaces or points) [vaultwarden]
#% DATA_LOCATION: Data localization (Example: /apps/service) [/apps]
#% URL: Service URL (Example: service.rotthier.net or service.com)
#% PORT: Your access port web (Example: 80) [80]
#% NETWORK: Your Traefik network (Example: proxy) [proxy]
#% SIGNUPS_ALLOWED: Autorize signup ? (True or False) [True]
#% TIME_ZONE: Time zone (Example : Europe/Paris) [Europe/Paris]
#% ADMIN_TOKEN: Admin token (For manage with url/admin)

# Work with Portainer
version: "3.8"
services:
  # Bitwarden : https://bitwarden.com/
  bitwarden:
    image: vaultwarden/server:latest
    container_name: $SERVICE
    restart: always
    volumes:
      - $DATA_LOCATION/$SERVICE/bw-data:/data
    environment:
      WEBSOCKET_ENABLED: 'true' # Required to use websockets
      SIGNUPS_ALLOWED: '$SIGNUPS_ALLOWED'   # set to false to disable signups
      TZ: '$TIME_ZONE'
      ADMIN_TOKEN: '$ADMIN_TOKEN'
    healthcheck:
      test: curl --fail http://localhost:80 || exit 1
      interval: 1m
      timeout: 30s
      retries: 3
    ports:
      - 3012:3012
    networks:
      - default
    labels:
      - "autoupdate=true" # https://github.com/Drack0rr/container-updater
      - "autoupdate.webhook="      
      - "traefik.enable=true"
      - "traefik.http.routers.$SERVICE.entrypoints=https"
      - "traefik.http.routers.$SERVICE.rule=Host(`$URL`)"
      - "traefik.http.routers.$SERVICE.tls=true"
      - "traefik.http.routers.$SERVICE.tls.certresolver=http"
      - "traefik.docker.network=$NETWORK"
networks:
  default:
    external:
      name: $NETWORK